name: Docker Build and Publish

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TAG: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build image
      run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/rest-set-game:$TAG

    - name: Push image
      run: docker push $DOCKER_USERNAME/rest-set-game:$TAG
